services:
  # Backend API Service
  - type: web
    name: doctorfollow-api
    env: python
    region: oregon
    plan: free
    rootDir: testing
    buildCommand: |
      cd iteration_3
      pip install --upgrade pip
      pip install -r ../requirements.txt
    startCommand: |
      cd iteration_3
      python api_server.py
    healthCheckPath: /health
    envVars:
      # Authentication
      - key: DEMO_USERNAME
        value: demo
      - key: DEMO_PASSWORD
        generateValue: true

      # CORS - UPDATE THIS AFTER FRONTEND DEPLOYMENT
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://doctorfollow.vercel.app

      # LLM Provider
      - key: LLM_PROVIDER
        value: openai
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini

      # PostgreSQL - Auto-linked from database below
      - key: DATABASE_URL
        fromDatabase:
          name: doctorfollow-db
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: doctorfollow-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: doctorfollow-db
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: doctorfollow-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: doctorfollow-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: doctorfollow-db
          property: password

      # Neo4j - SET THESE MANUALLY AFTER CREATING NEO4J AURA INSTANCE
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        sync: false

      # Elasticsearch/OpenSearch - SET THESE MANUALLY FOR ELASTIC CLOUD
      - key: ES_URL
        sync: false
      - key: ES_API_KEY
        sync: false
      - key: ES_INDEX_NAME
        value: medical_chunks

      # Embedding Configuration
      - key: EMBEDDING_MODEL
        value: intfloat/multilingual-e5-large
      - key: EMBEDDING_DIMENSION
        value: 1024

      # RAG Parameters
      - key: CHUNK_SIZE
        value: 400
      - key: CHUNK_OVERLAP
        value: 100
      - key: TOP_K_OPENSEARCH
        value: 10
      - key: TOP_K_PGVECTOR
        value: 10
      - key: TOP_K_FINAL
        value: 5
      - key: RRF_K
        value: 60

# PostgreSQL Database
databases:
  - name: doctorfollow-db
    databaseName: doctorfollow
    user: doctorfollow
    plan: free
    region: oregon
    postgresMajorVersion: 15
    ipAllowList: []
