services:
  # Backend API Service
  - type: web
    name: doctorfollow-api
    env: python
    region: oregon
    plan: free
    rootDir: testing
    buildCommand: |
      cd iteration_3
      pip install --upgrade pip
      pip install -r ../requirements.txt
    startCommand: |
      cd iteration_3
      python api_server.py
    healthCheckPath: /health
    envVars:
      # Authentication
      - key: DEMO_USERNAME
        value: demo
      - key: DEMO_PASSWORD
        generateValue: true

      # CORS - UPDATE THIS AFTER FRONTEND DEPLOYMENT
      - key: ALLOWED_ORIGINS
        value: http://localhost:3000,https://doctorfollow.vercel.app

      # LLM Provider
      - key: LLM_PROVIDER
        value: openai
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini

      # PostgreSQL - MANUALLY SET THESE FROM YOUR EXISTING DATABASE
      # Get these values from your existing Render PostgreSQL instance
      - key: POSTGRES_URL
        sync: false  # Set this manually with your existing database connection string

      # Neo4j - SET THESE MANUALLY AFTER CREATING NEO4J AURA INSTANCE
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        value: neo4j
      - key: NEO4J_PASSWORD
        sync: false

      # Elasticsearch/OpenSearch - SET THESE MANUALLY FOR ELASTIC CLOUD
      - key: ES_URL
        sync: false
      - key: ES_API_KEY
        sync: false
      - key: ES_INDEX_NAME
        value: doctor_follow_medical_chunks

      # Embedding Configuration (IMPORTANT: Must match your indexed embeddings!)
      - key: EMBEDDING_MODEL
        value: intfloat/multilingual-e5-small
      - key: EMBEDDING_DIMENSION
        value: 384

      # RAG Parameters
      - key: CHUNK_SIZE
        value: 400
      - key: CHUNK_OVERLAP
        value: 100
      - key: TOP_K_OPENSEARCH
        value: 10
      - key: TOP_K_PGVECTOR
        value: 10
      - key: TOP_K_FINAL
        value: 5
      - key: RRF_K
        value: 60

# No databases section - using existing database
